"""The diary and knowledge base: plain Markdown, one file per week or month.

Three rules shape everything here.

**Append only.** A note is written once, at the end of its period file, and the
line it lands on is its citation for ever. Corrections are new entries that link
back (`daybook note amend`), never edits, because rewriting a file that Dropbox
is halfway through syncing is how somebody's words get lost.

**The Markdown is the truth; every index is derived.** Reads parse the period
files themselves, so a stale index, a hand-typed entry or a half-finished write
can never make the tool report something false. Delete every index and
`reindex` rebuilds them byte for byte.

**No Beancount.** This module is stdlib plus `files` and `dates`, both of which
are dependency-free. Notes must work in a folder with no ledger in it at all;
resolving `--who` against ledger entities is done by the caller, if a ledger
happens to be reachable. Do not import `store`, `entities` or `contracts` here.
"""
from __future__ import annotations

import os
import re
import tomllib
from dataclasses import dataclass, field
from datetime import date, datetime, timedelta
from pathlib import Path

from .files import DaybookError, append_block, write_if_changed

LOCATION_FILENAME = ".daybook-notes-root"
ROOT_ENV_VAR = "DAYBOOK_NOTES_ROOT"
CONFIG_FILENAME = "notes.toml"
NOTES_DIRNAME = "notes"
PERIODS = ("week", "month")

GENERATED = "<!-- Generated by `daybook note`. Do not edit: run `daybook note reindex`. -->"

# A heading must carry both a date and a time, so an ordinary `## Subheading`
# inside somebody's prose is just prose and never splits their note in two.
HEADING = re.compile(r"^##\s+(\d{4}-\d{2}-\d{2})\s+(\d{2}:\d{2})\s+(.*\S)\s*$")
FACET = re.compile(r"^([a-z][a-z0-9_-]*):[ \t]*(.*)$")
INDEX_ENTRY = re.compile(r"^-\s+(\d{4}-\d{2}-\d{2})\s+(\d{2}:\d{2})\s+\[([^\]]*)\]\s+(.*\S)\s*$")
LIST_FACETS = ("who", "tags")
KNOWN_FACETS = ("kind", "who", "tags", "when", "source")
CONFLICT_MARKERS = ("conflicted copy", ".sync-conflict-", "(case conflict)")


# --------------------------------------------------------------- finding them

def _from_location_file(start: Path) -> Path | None:
    for candidate in [start, *start.parents]:
        pointer = candidate / LOCATION_FILENAME
        if pointer.exists():
            raw = pointer.read_text(encoding="utf-8").strip()
            if raw:
                return Path(raw).expanduser().resolve()
    return None


def _daybook_notes_dir() -> Path | None:
    """`<daybook root>/notes`, when a ledger is reachable from here.

    Imported lazily and forgivingly: a notes-only folder has no ledger, and
    reaching for one must not drag Beancount into a diary.
    """
    try:
        from .store import project_root
        return project_root() / NOTES_DIRNAME
    except Exception:  # noqa: BLE001 - no ledger is an ordinary state, not an error
        return None


def notes_root(start: Path | None = None, *, must_exist: bool = True) -> Path:
    """DAYBOOK_NOTES_ROOT, then a .daybook-notes-root pointer, then <daybook root>/notes, then ./notes."""
    env = os.environ.get(ROOT_ENV_VAR)
    if env:
        root = Path(env).expanduser().resolve()
        if not must_exist or (root / CONFIG_FILENAME).exists():
            return root
        raise DaybookError(
            f"{ROOT_ENV_VAR} is set to {root}, but no {CONFIG_FILENAME} was found there. "
            f"Run 'daybook note init {root}' to set it up."
        )
    here = (start or Path.cwd()).resolve()
    pointed = _from_location_file(here)
    if pointed is not None:
        if not must_exist or (pointed / CONFIG_FILENAME).exists():
            return pointed
        raise DaybookError(
            f"{LOCATION_FILENAME} points at {pointed}, but no {CONFIG_FILENAME} is there."
        )
    for candidate in (_daybook_notes_dir(), here / NOTES_DIRNAME, here):
        if candidate is not None and (candidate / CONFIG_FILENAME).exists():
            return candidate.resolve()
    if not must_exist:
        return here / NOTES_DIRNAME
    raise DaybookError(
        "No notes folder found. Run 'daybook note init <folder>' to make one, or put "
        f"the path to it in a {LOCATION_FILENAME} file."
    )


def read_config(root: Path) -> dict:
    path = root / CONFIG_FILENAME
    if not path.exists():
        raise DaybookError(f"{path} is missing. Run 'daybook note init {root}'.")
    try:
        with open(path, "rb") as handle:
            config = tomllib.load(handle)
    except tomllib.TOMLDecodeError as exc:
        raise DaybookError(f"{path} is not valid TOML: {exc}") from exc
    period = str(config.get("period", "week"))
    if period not in PERIODS:
        raise DaybookError(
            f"{path} says period = {period!r}, but it must be one of {', '.join(PERIODS)}."
        )
    return {"period": period}


def write_config(root: Path, period: str) -> Path:
    if period not in PERIODS:
        raise DaybookError(f"Period must be one of {', '.join(PERIODS)}, not {period!r}.")
    path = root / CONFIG_FILENAME
    write_if_changed(path, (
        "# How your notes are filed: one file per \"week\" or per \"month\".\n"
        "# Change this and run `daybook note reindex` to refile everything.\n"
        f'period = "{period}"\n'
    ))
    return path


# ------------------------------------------------------------------ the files

def period_key(when: date, period: str) -> str:
    """'2026-W37' or '2026-09'. In week mode the ISO year is used, so a week
    that straddles New Year stays one file instead of being torn in half."""
    if period == "week":
        iso_year, iso_week, _ = when.isocalendar()
        return f"{iso_year}-W{iso_week:02d}"
    return f"{when.year}-{when.month:02d}"


def period_file(root: Path, when: date, period: str) -> Path:
    key = period_key(when, period)
    return root / key.split("-")[0] / f"{key}.md"


def period_bounds(key: str) -> tuple[date, date]:
    """First and last day covered by a period key."""
    if "W" in key:
        year, week = key.split("-W")
        start = date.fromisocalendar(int(year), int(week), 1)
        return start, start + timedelta(days=6)
    year, month = (int(part) for part in key.split("-"))
    start = date(year, month, 1)
    end = date(year + (month == 12), month % 12 + 1, 1) - timedelta(days=1)
    return start, end


def period_header(key: str) -> str:
    start, end = period_bounds(key)
    if "W" in key:
        span = (f"{start.strftime('%A')} {start.day} {start.strftime('%B')}"
                f" - {end.strftime('%A')} {end.day} {end.strftime('%B %Y')}")
        return f"# Week {int(key.split('-W')[1])}, {start.isocalendar()[0]}\n# {span}\n"
    return f"# {start.strftime('%B %Y')}\n"


def _period_files(root: Path) -> list[Path]:
    """Every note file, in date order, skipping generated indexes."""
    found = [
        p for p in root.glob("*/*.md")
        if not p.name.startswith("INDEX")
        and not any(marker in p.name for marker in CONFLICT_MARKERS)
    ]
    return sorted(found, key=lambda p: p.stem)


# --------------------------------------------------------------------- a note

@dataclass
class Note:
    date: date
    time: str
    title: str
    kind: str = "note"
    who: list[str] = field(default_factory=list)
    tags: list[str] = field(default_factory=list)
    when: str = ""
    source: str = ""
    facets: dict[str, str] = field(default_factory=dict)
    body: str = ""
    file: str = ""
    line: int = 0

    @property
    def citation(self) -> str:
        return f"{self.file}:{self.line}" if self.file else ""

    def to_dict(self) -> dict:
        out = {
            "date": self.date.isoformat(), "time": self.time, "title": self.title,
            "kind": self.kind, "who": self.who, "tags": self.tags,
            "citation": self.citation,
        }
        if self.when:
            out["when"] = self.when
        if self.source:
            out["source"] = self.source
        if self.facets:
            out["facets"] = dict(self.facets)
        if self.body:
            out["body"] = self.body
        return out

    def haystack(self) -> str:
        return " \n".join([
            self.title, self.kind, ", ".join(self.who), ", ".join(self.tags),
            self.when, self.source, *self.facets.values(), self.body,
        ]).casefold()


def _split_list(raw: str) -> list[str]:
    return [part.strip() for part in raw.split(",") if part.strip()]


def render(note: Note) -> str:
    """One entry, exactly as it is stored."""
    lines = [f"## {note.date.isoformat()} {note.time}  {note.title}"]
    ordered = {
        "kind": note.kind,
        "who": ", ".join(note.who),
        "tags": ", ".join(note.tags),
        "when": note.when,
        "source": note.source,
        **note.facets,
    }
    for key, value in ordered.items():
        if str(value).strip():
            lines.append(f"{key}: {value}")
    body = note.body.strip("\n")
    if body:
        lines.append("")
        lines.append(_escape_body(body))
    return "\n".join(lines) + "\n"


def _escape_body(body: str) -> str:
    """Indent any body line that would otherwise look like a new entry's
    heading to the parser (`HEADING`'s `^##  YYYY-MM-DD HH:MM ...`).

    A note is free to quote or paste anything, including another note's own
    heading line -- inside `note amend`, for instance. Without this, such a
    line would silently split one note into two and shift every citation
    after it. Indenting by two spaces keeps the text as plain Markdown and
    keeps the line count -- and so every later citation -- unchanged.
    """
    return "\n".join(
        f"  {line}" if HEADING.match(line) else line
        for line in body.split("\n")
    )


def parse_text(text: str, file: str = "") -> list[Note]:
    """Every entry in one period file.

    A `## ` line carrying a date and a time opens an entry; the `key: value`
    lines directly under it are its facets; the first blank line ends them, and
    everything up to the next entry is the body.
    """
    notes: list[Note] = []
    lines = text.splitlines()
    index = 0
    while index < len(lines):
        match = HEADING.match(lines[index])
        if not match:
            index += 1
            continue
        day, clock, title = match.groups()
        try:
            when = date.fromisoformat(day)
        except ValueError:
            index += 1
            continue
        note = Note(date=when, time=clock, title=title.strip(), kind="",
                    file=file, line=index + 1)
        index += 1
        while index < len(lines) and lines[index].strip():
            facet = FACET.match(lines[index])
            if not facet:
                break
            key, value = facet.group(1), facet.group(2).strip()
            if key in LIST_FACETS:
                setattr(note, key, _split_list(value))
            elif key in KNOWN_FACETS:
                setattr(note, key, value)
            else:
                note.facets[key] = value
            index += 1
        body: list[str] = []
        while index < len(lines) and not HEADING.match(lines[index]):
            body.append(lines[index])
            index += 1
        note.kind = note.kind or "note"
        note.body = "\n".join(body).strip("\n")
        notes.append(note)
    return notes


def parse_file(path: Path, root: Path | None = None) -> list[Note]:
    if not path.exists():
        return []
    name = path.relative_to(root).as_posix() if root else path.name
    return parse_text(path.read_text(encoding="utf-8"), name)


def load_notes(root: Path, *, since: date | None = None, until: date | None = None) -> list[Note]:
    """Every note in range, read from the Markdown itself.

    Reads are answered from the files rather than the indexes on purpose: an
    index that is behind can then never cause a wrong answer, only a folder
    that looks untidy until `reindex` runs.
    """
    notes: list[Note] = []
    for path in _period_files(root):
        try:
            start, end = period_bounds(path.stem)
        except (ValueError, IndexError):
            continue  # not a period file; leave whatever it is alone
        if since and end < since:
            continue
        if until and start > until:
            continue
        for note in parse_file(path, root):
            if since and note.date < since:
                continue
            if until and note.date > until:
                continue
            notes.append(note)
    notes.sort(key=lambda n: (n.date, n.time, n.file, n.line))
    return notes


# ------------------------------------------------------------------- indexes

def _month_index_path(root: Path, year: int, month: int) -> Path:
    return root / str(year) / f"INDEX-{year}-{month:02d}.md"


def _year_index_path(root: Path, year: int) -> Path:
    return root / str(year) / f"INDEX-{year}.md"


def _counts(values) -> list[tuple[str, int]]:
    tally: dict[str, int] = {}
    for value in values:
        tally[value] = tally.get(value, 0) + 1
    return sorted(tally.items(), key=lambda kv: (-kv[1], kv[0].casefold()))


def render_month_index(year: int, month: int, notes: list[Note]) -> str:
    label = date(year, month, 1).strftime("%B %Y")
    lines = [f"# {label} - {len(notes)} note{'s' if len(notes) != 1 else ''}", GENERATED, ""]
    for note in notes:
        lines.append(
            f"- {note.date.isoformat()} {note.time} [{note.kind}] {note.title}"
        )
        details = []
        if note.who:
            details.append("who: " + ", ".join(note.who))
        if note.tags:
            details.append("tags: " + ", ".join(note.tags))
        if note.when:
            details.append("when: " + note.when)
        details.append(note.citation)
        lines.append("  " + " | ".join(details))
    return "\n".join(lines) + "\n"


def parse_month_index(path: Path) -> list[dict]:
    """Read a month index back. Used for the rollups and by anything browsing
    the folder without this tool; never used to decide what a note says."""
    if not path.exists():
        return []
    rows: list[dict] = []
    lines = path.read_text(encoding="utf-8").splitlines()
    for i, line in enumerate(lines):
        match = INDEX_ENTRY.match(line)
        if not match:
            continue
        day, clock, kind, title = match.groups()
        row = {"date": day, "time": clock, "kind": kind, "title": title,
               "who": [], "tags": [], "when": "", "citation": ""}
        if i + 1 < len(lines) and lines[i + 1].startswith("  "):
            parts = [p.strip() for p in lines[i + 1].strip().split(" | ")]
            row["citation"] = parts[-1]
            for part in parts[:-1]:
                key, _, value = part.partition(": ")
                if key in LIST_FACETS:
                    row[key] = _split_list(value)
                elif key == "when":
                    row["when"] = value
        rows.append(row)
    return rows


def render_year_index(year: int, months: dict[int, list[dict]]) -> str:
    total = sum(len(rows) for rows in months.values())
    everything = [row for rows in months.values() for row in rows]
    days = sorted(row["date"] for row in everything)
    lines = [f"# {year} - {total} note{'s' if total != 1 else ''}", GENERATED, ""]
    if days:
        lines += [f"{days[0]} to {days[-1]}", ""]
    lines += ["| Month | Notes | Index |", "|---|---|---|"]
    for month in sorted(months):
        if not months[month]:
            continue
        label = date(year, month, 1).strftime("%B")
        name = f"INDEX-{year}-{month:02d}.md"
        lines.append(f"| {label} | {len(months[month])} | [{name}]({name}) |")
    tags = _counts(tag for row in everything for tag in row["tags"])
    people = _counts(who for row in everything for who in row["who"])
    kinds = _counts(row["kind"] for row in everything)
    for heading, tally in (("Tags", tags), ("People", people), ("Kinds", kinds)):
        if tally:
            lines += ["", f"## {heading}", "",
                      " · ".join(f"{name} ({count})" for name, count in tally)]
    return "\n".join(lines) + "\n"


def render_root_index(years: dict[int, int], span: tuple[str, str] | None) -> str:
    total = sum(years.values())
    plural = "s" if len(years) != 1 else ""
    lines = [f"# Notes - {total} across {len(years)} year{plural}", GENERATED, ""]
    if span:
        lines += [f"{span[0]} to {span[1]}", ""]
    lines += ["| Year | Notes | Index |", "|---|---|---|"]
    for year in sorted(years, reverse=True):
        name = f"{year}/INDEX-{year}.md"
        lines.append(f"| {year} | {years[year]} | [{name}]({name}) |")
    return "\n".join(lines) + "\n"


def refresh_month(root: Path, year: int, month: int) -> Path:
    """Rewrite one month index from the notes that belong to that month.

    Bounded by the month, never by the corpus: this is what keeps a write the
    same cost on day one and in year ten.
    """
    start = date(year, month, 1)
    end = date(year + (month == 12), month % 12 + 1, 1) - timedelta(days=1)
    notes = load_notes(root, since=start, until=end)
    path = _month_index_path(root, year, month)
    if not notes:
        if path.exists():
            path.unlink()
        return path
    write_if_changed(path, render_month_index(year, month, notes))
    return path


def refresh_year(root: Path, year: int) -> Path:
    """Rewrite one year rollup **from its month indexes**, not from the notes.

    A rollup built by re-reading every note file would make each write cost
    grow with the year. Twelve small index files is a fixed price.
    """
    months = {
        month: parse_month_index(_month_index_path(root, year, month))
        for month in range(1, 13)
    }
    path = _year_index_path(root, year)
    if not any(months.values()):
        if path.exists():
            path.unlink()
        return path
    write_if_changed(path, render_year_index(year, months))
    return path


def refresh_root(root: Path) -> Path:
    """Rewrite the top-level index from the year rollups."""
    years: dict[int, int] = {}
    span: list[str] = []
    for year_dir in sorted(root.glob("[0-9][0-9][0-9][0-9]")):
        if not year_dir.is_dir():
            continue
        year = int(year_dir.name)
        rows = [
            row
            for month in range(1, 13)
            for row in parse_month_index(_month_index_path(root, year, month))
        ]
        if rows:
            years[year] = len(rows)
            span += [row["date"] for row in rows]
    path = root / "INDEX.md"
    if not years:
        if path.exists():
            path.unlink()
        return path
    bounds = (min(span), max(span)) if span else None
    write_if_changed(path, render_root_index(years, bounds))
    return path


def refresh_for(root: Path, when: date) -> list[Path]:
    """Every index affected by a note on this date, cheapest first."""
    return [
        refresh_month(root, when.year, when.month),
        refresh_year(root, when.year),
        refresh_root(root),
    ]


def reindex(root: Path) -> dict:
    """Rebuild every index from the Markdown. The files are the truth; this
    just makes the folder describe itself again."""
    for stale in root.glob("*/INDEX-*.md"):
        stale.unlink()
    if (root / "INDEX.md").exists():
        (root / "INDEX.md").unlink()
    notes = load_notes(root)
    months = sorted({(n.date.year, n.date.month) for n in notes})
    for year, month in months:
        refresh_month(root, year, month)
    for year in sorted({year for year, _ in months}):
        refresh_year(root, year)
    refresh_root(root)
    return {
        "root": str(root), "notes": len(notes), "months": len(months),
        "years": len({year for year, _ in months}),
    }


# ------------------------------------------------------------------- writing

def add_note(root: Path, note: Note, *, period: str) -> dict:
    """Append one entry and bring the indexes back in step."""
    if not note.title.strip():
        raise DaybookError("A note needs a title: it is all the index shows.")
    path = period_file(root, note.date, period)
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(period_header(path.stem), encoding="utf-8")
    line = append_block(path, render(note))
    note.file = path.relative_to(root).as_posix()
    note.line = line
    touched = [path, *refresh_for(root, note.date)]
    return {
        "status": "recorded",
        "note": note.to_dict(),
        "citation": note.citation,
        "file": str(path),
        "files_touched": [p.relative_to(root).as_posix() for p in touched if p.exists()],
    }


def amend(root: Path, citation: str, body: str, *, period: str,
          at: date | None = None, time: str | None = None) -> dict:
    """Correct a note by appending one that links back to it.

    The original stays exactly where it is, because its citation may already
    have been quoted in an answer, in another note, or to another person.
    """
    original = find_by_citation(root, citation)
    if original is None:
        raise DaybookError(f"No note at {citation}. Run 'daybook note find' to get a citation.")
    when = at or date.today()
    note = Note(
        date=when,
        time=time or datetime.now().strftime("%H:%M"),
        title=f"Amends: {original.title}",
        kind="amendment",
        who=list(original.who),
        tags=list(original.tags),
        facets={"amends": citation},
        body=body,
    )
    result = add_note(root, note, period=period)
    result["amends"] = original.to_dict()
    return result


# ------------------------------------------------------------------- reading

def find_by_citation(root: Path, citation: str) -> Note | None:
    file, _, line = citation.rpartition(":")
    if not file or not line.isdigit():
        raise DaybookError(
            f"{citation!r} is not a citation. They look like '2026/2026-W37.md:5'."
        )
    path = root / file
    for note in parse_file(path, root):
        if note.line == int(line):
            return note
    return None


def _snippet(note: Note, needle: str, width: int = 200) -> str:
    text = note.body.replace("\n", " ").strip()
    if not text:
        return ""
    position = text.casefold().find(needle) if needle else 0
    if position < 0:
        return text[:width] + ("..." if len(text) > width else "")
    start = max(0, position - width // 3)
    end = min(len(text), start + width)
    return ("..." if start else "") + text[start:end] + ("..." if end < len(text) else "")


def _score(note: Note, needle: str) -> int:
    if not needle:
        return 1
    score = 0
    if needle in note.title.casefold():
        score += 4
    if any(needle in tag.casefold() for tag in note.tags):
        score += 3
    if any(needle in who.casefold() for who in note.who):
        score += 3
    if needle in note.body.casefold():
        score += 2
    if needle in note.haystack():
        score += 1
    return score


def find(root: Path, text: str = "", *, who: list[str] | None = None,
         tags: list[str] | None = None, kind: str = "",
         since: date | None = None, until: date | None = None,
         limit: int = 20) -> dict:
    needle = text.strip().casefold()
    wanted_who = [w.casefold() for w in (who or [])]
    wanted_tags = [t.casefold() for t in (tags or [])]
    hits = []
    for note in load_notes(root, since=since, until=until):
        if kind and note.kind.casefold() != kind.casefold():
            continue
        if wanted_who and not all(
            any(w in name.casefold() for name in note.who) for w in wanted_who
        ):
            continue
        if wanted_tags and not all(
            any(t in tag.casefold() for tag in note.tags) for t in wanted_tags
        ):
            continue
        score = _score(note, needle)
        if needle and score == 0:
            continue
        row = note.to_dict()
        row.pop("body", None)
        row["snippet"] = _snippet(note, needle)
        hits.append((score, note.date, note.time, row))
    # Best match first, then most recent. Two passes so the second, stable
    # sort keeps the recency order inside each score band.
    hits.sort(key=lambda h: h[2], reverse=True)
    hits.sort(key=lambda h: (-h[0], -h[1].toordinal()))
    rows = [row for _, _, _, row in hits]
    return {
        "query": text, "matches": len(rows), "shown": min(len(rows), limit),
        "results": rows[:limit],
    }


def topic(root: Path, tag: str, limit: int = 50) -> dict:
    """Everything filed under one tag. A topic is a query, not a second store,
    so nothing is written twice and nothing can go out of date."""
    needle = tag.strip().casefold()
    notes = [n for n in load_notes(root) if any(needle == t.casefold() for t in n.tags)]
    notes.sort(key=lambda n: (n.date, n.time), reverse=True)
    also = _counts(t for n in notes for t in n.tags if t.casefold() != needle)
    return {
        "topic": tag,
        "matches": len(notes),
        "first": notes[-1].date.isoformat() if notes else "",
        "last": notes[0].date.isoformat() if notes else "",
        "people": [{"name": n, "notes": c} for n, c in _counts(w for x in notes for w in x.who)],
        "also_tagged": [{"tag": t, "notes": c} for t, c in also],
        "results": [
            {k: v for k, v in n.to_dict().items() if k != "body"} for n in notes[:limit]
        ],
    }


def tally(root: Path, what: str) -> dict:
    """How often each tag, person or kind appears, counted from the notes."""
    notes = load_notes(root)
    values = (
        (tag for n in notes for tag in n.tags) if what == "tags"
        else (who for n in notes for who in n.who) if what == "people"
        else (n.kind for n in notes)
    )
    return {
        what: [{"name": name, "notes": count} for name, count in _counts(values)],
        "notes": len(notes),
    }


def _when_range(raw: str) -> tuple[date, date] | None:
    parts = [p.strip() for p in raw.split("..")]
    try:
        start = date.fromisoformat(parts[0])
        end = date.fromisoformat(parts[1]) if len(parts) > 1 else start
    except (ValueError, IndexError):
        return None
    return (start, end) if end >= start else (end, start)


def agenda(root: Path, days: int = 30, frm: date | None = None) -> dict:
    """Notes carrying a `when:` that falls in the window.

    This is the surface a scheduled agent asks: "what is coming up". It reports
    what was written down and nothing else -- deciding what to do about a booked
    trip is not this tool's job.
    """
    start = frm or date.today()
    end = start + timedelta(days=days)
    rows = []
    for note in load_notes(root):
        if not note.when:
            continue
        span = _when_range(note.when)
        if span is None:
            continue
        begins, finishes = span
        if finishes < start or begins > end:
            continue
        row = {k: v for k, v in note.to_dict().items() if k != "body"}
        row["starts"] = begins.isoformat()
        row["ends"] = finishes.isoformat()
        row["days_until"] = (begins - start).days
        rows.append(row)
    rows.sort(key=lambda r: (r["starts"], r["ends"]))
    return {"from": start.isoformat(), "to": end.isoformat(), "window_days": days,
            "entries": rows}


def period_view(root: Path, when: date, period: str) -> dict:
    key = period_key(when, period)
    path = period_file(root, when, period)
    start, end = period_bounds(key)
    notes = parse_file(path, root)
    return {
        "period": key, "from": start.isoformat(), "to": end.isoformat(),
        "file": path.relative_to(root).as_posix() if path.exists() else "",
        "notes": len(notes),
        "results": [n.to_dict() for n in notes],
    }


def on_date(root: Path, when: date) -> dict:
    notes = load_notes(root, since=when, until=when)
    return {"on": when.isoformat(), "notes": len(notes),
            "results": [n.to_dict() for n in notes]}


def find_conflicts(root: Path) -> dict:
    """Files a sync client made because two devices wrote at once.

    Reported, never merged: picking which of two versions of somebody's own
    words survives is a decision for them, not for this tool.
    """
    suspects = sorted(
        p.relative_to(root).as_posix()
        for p in root.rglob("*")
        if p.is_file() and any(marker in p.name for marker in CONFLICT_MARKERS)
    )
    notes = load_notes(root)
    stale = []
    for year, month in sorted({(n.date.year, n.date.month) for n in notes}):
        path = _month_index_path(root, year, month)
        expected = render_month_index(
            year, month,
            [n for n in notes if (n.date.year, n.date.month) == (year, month)],
        )
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            stale.append(path.relative_to(root).as_posix())
    return {
        "root": str(root),
        "notes": len(notes),
        "sync_conflicts": suspects,
        "stale_indexes": stale,
        "status": "ok" if not suspects and not stale else "needs_attention",
        "detail": (
            "Nothing to do."
            if not suspects and not stale
            else "Run 'daybook note reindex' to rebuild the indexes. "
                 "Sync conflict files are left for you to merge by hand."
        ),
    }


def init(folder: Path, period: str = "week") -> dict:
    folder = folder.expanduser().resolve()
    folder.mkdir(parents=True, exist_ok=True)
    config = write_config(folder, period)
    refresh_root(folder)
    return {"notes_folder": str(folder), "period": period, "config": str(config)}
